# Project: 学生管理系统
# Makefile created by Red Panda C++ 3.3.3147

CXX      = "g++.exe"
CC       = "gcc.exe"
WINDRES  = "windres.exe"
RM       = del /q /f
CD       = cd /d
LIBS     = "-Wl,--stack,12582912"
INCS     = 
CXXINCS  = 
CXXFLAGS = $(CXXINCS) "-g3" "-pipe" "-Wall" "-D_DEBUG"
CFLAGS   = $(INCS) "-g3" "-pipe" "-Wall" "-D_DEBUG"
WINDRESFLAGS = 
RES      = 学生管理系统_private.res
OBJ      = input.o link.o student.o output.o main.o $(RES)
BIN      = 学生管理系统.exe
LINKOBJ  = "input.o" "link.o" "student.o" "output.o" "main.o" "学生管理系统_private.res"
CLEANOBJ = "input.o" "link.o" "student.o" "output.o" "main.o" "学生管理系统_private.res" "学生管理系统.exe"

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	-$(RM) $(CLEANOBJ) >NUL 2>&1

学生管理系统.exe: $(OBJ)

	$(CXX) $(LINKOBJ) -o "学生管理系统.exe" $(LIBS)

input.o: input.cpp public_defs.h input.h student.h link.h
	$(CXX) -c "input.cpp" -o "input.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

link.o: link.cpp public_defs.h link.h
	$(CXX) -c "link.cpp" -o "link.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

student.o: student.cpp public_defs.h output.h input.h student.h link.h
	$(CXX) -c "student.cpp" -o "student.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

output.o: output.cpp public_defs.h output.h student.h link.h
	$(CXX) -c "output.cpp" -o "output.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

main.o: main.cpp public_defs.h output.h input.h student.h link.h
	$(CXX) -c "main.cpp" -o "main.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

学生管理系统_private.res: 学生管理系统_private.rc 
	$(WINDRES) -i "学生管理系统_private.rc" --input-format=rc -o "学生管理系统_private.res" -O coff $(WINDRESFLAGS) 

